version: 2.1
jobs:
  commit:
    docker:
      - image: jakzal/phpqa:php8.0-alpine
    steps:
      - checkout
      - run:
          name: install dependancies
          command: composer install
      - run:
          name: commit stage
          command: ./bin/phing commit-stage
      - store_test_results:
          path: reports/phpunit
      - store_artifacts:
          path: reports

workflows:
  deployment_pipeline:
    jobs:
      - commit
