version: 2.1
jobs:
  commit:
    docker:
      - image: cimg/php:8.0.8
    steps:
      - checkout
      - run: composer install
      - run: ./bin/phing commit-stage

workflows:
  deployment_pipeline:
    jobs:
      - commit
