version: 2.1
jobs:
  commit:
    docker:
      - image: cimg/php:8.0.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-deps-{{ checksum "composer.lock" }}
      - restore_cache:
          keys:
            - v1-binary-deps
      - run:
          name: install dependancies
          command: composer install
      - run:
          name: commit stage
          command: ./bin/phing commit-stage
      - store_test_results:
          path: reports/phpunit
      - store_artifacts:
          path: reports
      - save_cache:
          key: v1-composer-deps-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - save_cache:
          key: v1-binary-deps
          paths:
            - bin

workflows:
  deployment_pipeline:
    jobs:
      - commit
